adding explicit float to int conversion to avoid twedit crashes with …
CompuCell3D/cc3d-twedit5 pull request #31
Opened 2023-07-27 17:55 UTC by maciekswat

…the new PyQt when cycling through twedit tabs

2023-08-13 22:29 UTC, tjsego requested changes
Looks good, except that __init__ needs cleaned.

2023-08-13 22:29 UTC, tjsego commented on cc3d/__init__.py
I think this was uploaded by mistake.

2023-08-13 22:50 UTC, maciekswat commented on cc3d/__init__.py
Obviously. good catch!

2023-08-14 01:43 UTC, tjsego approved these changes

2023-08-19 17:07 UTC, closed without merging